apiVersion: v1
data:
    apiKey: ENC[AES256_GCM,data:+Sa7WunRq+vD0RP1raU5rBBDKtfSFLdCJOORRj3WJ//KakvAZRsqj5N0qaixbabr5+BlBEclO38=,iv:EwerTPZwNDFgrPy+4TfdRZsnUcysXvXGU+vbpaZldc8=,tag:x9dK0S8uNdNRjCcg8skyVQ==,type:str]
    email: ENC[AES256_GCM,data:+KQnLNND8jOLtrGDkgeLhrbsYgFZbxF+SrSfrA==,iv:uDwemXHrP/VaTue801R+nXXTTnwPK5mZekBzRkFNCcs=,tag:HJ4PTUQ5Mi9BA93GBxQ0VA==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
sops:
    age:
        - recipient: age109xdd5ywsu28982323hmkzdmnrecrargr2dzqrjk843m4uu4yp5q9kasxe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcjM1MTNtaGlYWXluWk5v
            eERIZURsV24yOUM0VmQwVkRsbHVyVnZIdUE0CldaaW9uMFFjdUh3OG1raWxoTmNX
            dEFwUldPdXBrb1FpRjljc0tCamZJVGcKLS0tIGxUR1RNcll0VFNCOXlOY2xqTjNq
            bG05bytuZVBZaUduWnAyM056NVhJVnMKjXTBN+2+p4uzFK8KWkGwZmr4Syq+zs45
            IdOMRVXYdKS402VF5v+Lg4XnYfceKPywJPOXuMVxLmgzcwHwnSM7DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T07:47:10Z"
    mac: ENC[AES256_GCM,data:/bF2155AmZSJhOEdMPlPwdaAL/OSV9H2TBTM+EezwJybvjQNwKjyRd9SECuGLCLS1GhEaXhnAwy94taww2tAbTodxaNdv70zeft5Q7mgIaydBe3d+JRYjGM82lAJmMOznyoFiilC5bnp/eJaf2R6AH2LoWhLbmET/RvHQSI2G3M=,iv:Ar3u+yknATdD/CACZeh7uCHoNT1+Dq0zXrquQMF0syU=,tag:xPwUfcrKUx26cSx/6Fje8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
