---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.17.0
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 30m
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    sources:
      - ingress
    policy: sync
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: cloudflare-api-token
