apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - ingress-nginx
  - cloudflared
  - external-dns
  - argocd
  # - sealed-secrets
  # - headlamp
  # - flagger
  # - kyverno
  # - kyverno-policies
  # - metrics-server
