---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: argo-cd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      version: 9.4.3
  install:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
    timeout: 10m0s
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
    timeout: 10m0s
  interval: 1h0m0s
  storageNamespace: flux-system
  targetNamespace: argocd
  values:
    applicationSet:
      replicas: 2
    controller:
      replicas: 1
    global:
      domain: argocd.hariharanep4.xyz
    redis-ha:
      enabled: true
    repoServer:
      autoscaling:
        enabled: true
        minReplicas: 2
    configs:
      params:
        server.insecure: true
    server:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/hostname: argocd.hariharanep4.xyz
          external-dns.alpha.kubernetes.io/target: 242b49e3-7a13-4df0-8d63-0d7e2def744b.cfargotunnel.com
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        ingressClassName: "nginx"
        hosts:
        - argocd.hariharanep4.xyz
      
