Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.define "controlplane" do |controlplane|
        controlplane.vm.hostname = "controlplane"
        controlplane.vm.network "private_network", ip: "192.168.56.10"
        controlplane.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = 4
        end
    end

    worker_count = 2
    (1..worker_count).each do |i|
        config.vm.define "worker#{i}" do |worker|
            worker.vm.hostname = "worker#{i}"
            worker.vm.network "private_network", ip: "192.168.56.1#{i}"
            worker.vm.provider "virtualbox" do |vb|
                vb.memory = "4096"
                vb.cpus = 4
            end
        end
    end
end
