---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.11.x
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  upgrade:
    crds: CreateReplace
  values:
    controller:
      admissionWebhooks:
        certManager:
          enabled: true
