---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.14.0
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
    timeout: 5m0s
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
    timeout: 5m0s
  interval: 10m
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  # values:
  #   controller:
  #     admissionWebhooks:
  #       enabled: false
  #     service:
  #       type: ClusterIP
