---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.14.0
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  install:
    crds: Create
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  interval: 12h
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      admissionWebhooks:
        certManager:
          enabled: true
