hostUsers: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  privileged: false
  runAsUser: 100
  runAsGroup: 101
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: "26016222-ecef-4643-b9b5-0a28c04de49c.cfargotunnel.com"
    external-dns.alpha.kubernetes.io/hostname: headlamp.hariharanep4.space
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  ingressClassName: "nginx"
  hosts:
  - host: headlamp.hariharanep4.space
    paths:
    - path: /
      type: ImplementationSpecific
