apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:p64q0xgiYDwjLAd8RMizApM7xt76VlMBgK1bm7mXhn+MrtinLZzeV2e3yQIxqbg0QRBm/nAFDdaAOdDIutiB2uFdhWnsABVaw7fx5mCx3OUgTGgOLWPVigO6tI6ooo8kycAHkzgtAFPXVz2aKYQzBLl7OnkCA7bSCE2NX2Z5IeSy1jVHw4Lg+6RDGWX5OAboiQ1mPeue+R49Y/mxF2FDk8e+NJjrbc+k8EVV7ZEG68a0UbwlZVEtvlGyo3WhaAZxIlLO3/JZ5GpyHkfgvcjzxlC4laV82xdnjYq/Bu8pRACQlAoxxe2BznMgXqw=,iv:yGGdisH2QtzVJlwgwx7J7iWrMIO9Ia8dcfLLaB0xmuQ=,tag:1Rdb+PJsyDJB3ipj9Sxg9g==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age1gzd82msnwqs7x055svdf5h6axtgduzlrlh30hamwgkfp0edylc9s5xugg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV0c3TGdyQ1ZiOGQzREcy
            RWNhaUJudnhpTlI1Mm5iWjZGOEpmS1ZMK3hBCkRaSnVVZ3Y2dG4vaWRMa3owd0lM
            d1pyV0xIV1FBRlF5cy9TSlBIdXB4N2MKLS0tIHo2eW9oQTZybzRMSmI0SDVWMzNx
            eGp6R1lya0FIM1drbVlOWFNibE5PMTQKmFG3pzu9XTndVGn6umvSkeR85bh85vcz
            u7xF4yt0+XB/oNzi4G6t6rVSKDEUJ/cJWUDmUb7kqo1vJadD7l2Iig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T16:36:17Z"
    mac: ENC[AES256_GCM,data:KSQmJlXCTieEuEou6tAldQ4PG+H3r+kul29y+NC6EuoC5FlVTn5dM32KggrGPWsfYivNDfqFqhwI6vawo3YQApUMrj8RbihQovgE7OYCBXQMvaBaI2jaEtJoTdVUBpEEToa4S+NClX9xb578oJz/wnlb7eiSy8Gdo1XbavE7jIg=,iv:ZpDKQQS8sSFovMpclha4pVwFkrH0qI7i7lf+xLjzM7U=,tag:+9khO3EkavRZsKzZVQgcBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
