apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rRIAHePFI/kO0AfBVfRv/lJHi5489iFQqOD8F71JyTJSQ+GcVk8XUajSVfzY62t4aTu88TuBsFP1b9oOPThPBibU00Cb8k7mSrcowoF/PlcRBc+m7Jp+4K79/36tVr4iQfb4IkA528mpIflQ1oUgd0/AkDbldpMR8A6+WiODYCzL1/48lNLs30FGb4/CAaItatxaD6iHpS/WVzfRpe5TGCiOp1zG8vPGmJu6jB0Ld8jdaDcBEfiHLkxoHw3YnV67OUXpH2diEG7Bq/aomZ61Ea3nINXLbdKitu4brqdl+vtYjce6eUDDGfxsL+c=,iv:HubFIfydBRNEo6J0MucelbgzwOyad2t5lZ8vF+2PqMk=,tag:ovS7nXvZh148ZvVk/j62VA==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age1helqcqsh9464r8chnwc2fzj8uv7vr5ntnsft0tn45v2xtz0hpfwq98cmsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRWs2enNHZ2RFbU9lNHVh
            VGlkNlJaSXd0RGl4V3BnbHlLYWVlNm96MVVvClFsRFlQMWFuTnFkSVU0dnRLeEls
            SG0va2pVUzV1WTZybjg0VHJOR1RPQkUKLS0tIFZCdTdmZnBZd1liaEpZVk9FU1Ji
            WUM3bjZxNWhxd0czSHlYK1BDQlhJaFkKc1b7i0EW9uh8marDDfji0gf7CCljDTTj
            gHND216qRF1acWo2C/bxtRrSUNRP4/QPh1L3FCAnM4EOzeyMjGlb4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T16:24:48Z"
    mac: ENC[AES256_GCM,data:G4uw3Gt2jf2qavP9i5QZoYwoYRQSOan11BMi83twO3NyS/Qx1Qu/j2e99I+jh1/siy9liTD9DDJ+ltnenF9CbmaxX6Vj3QXRCVb60edPnSB0+44a+tmsH8n8m0yn3dHfvCNxMnhX7ebvf3FULXllWRl1ooA4CnK9UNuM5OUmE14=,iv:Gp7iTU04MQ2ZC6NRe8LoDMocGvOhOlw/mEyLoPYvwKk=,tag:p/k+vux0xIjxM2ymU1CrRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
