apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0DHe6DGgFX/ESAe5DF9ePeJlhLOypmHT0au4Fl0dxTYEWWwe/xTG+Fdt3sQB8iNvCpVTQbfsFOhEBHilPxniVaQG8uELH3ZAcq5sdhvQpkojauW3o+tJ3eMrHzoLWukip6EJ8gw0kAGef9dH74P6U71/R+k9W6a1Pq6Kcay34/3mVKV9lBOuN+3s6vjATi2vkydrj9Tx6rkGfBXBL5dY5MKSZyLzP4VQ3h1L08BszziSazcM4V0hhkXlRqzMwio02d+IeeQOF9lNOBCG31EqEP5AE9OgQlKELS69tWdZ8et/WXdI7q4ovP/rcPw=,iv:FPSAJFfunFW7bm1ZfCSZnoc7JuJvDrKHLrHEEhXdThw=,tag:N6o6XjyL4gV2lGmu0JWHLg==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTjhpWTdOK1NhdUhzNm1j
            WmNYK3lET0wyQVB6OTB0eUlwQXVUQTFldHkwCk1UeFN2Vy9tenYrUFhGdU43M0dk
            YXpZZk4yUmhUZ0NqUWxucG16TE9BNFkKLS0tIGg4cTNxSnRkVWt4NGZ6M1Bod0xP
            eTU1a1JmZXk2V1lXb2lNb3hmYlUwTlEK8ZAgE8ujNyPpQaIZTsohxjRkCz2bkDeH
            aDMB1tmYTaJzRpV85eCpu0oTe+fgWtIuHwV3s2EUNNOf1TU2uBjRsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ae4m9280dcywrzl2auxcttgpwp0lfhn4v48sqg5wh7c745r80a2qeq8fxy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-09T08:36:26Z"
    mac: ENC[AES256_GCM,data:oHfG1Ukhux5mOOyf4f3IJtqcHK+9Jy4CbIlDa5hz2+Dz5H69m9hhQmmoj6cbLg5Kb+0KAy/myR8Oyl48KUBzCMZ/guX0COlr3WElJshn8gleSvoP+00uB5Q/9qEHXkUWih73kgO8nA5peanSszRIG/7jo4KKjp7RJ0yIb7vX7Tw=,iv:bSBZU5My7ez81V5lWLtUCmSgu6QBpcglKvoeg5YY1SI=,tag:7QRCLFZ2mTiKhrooYt1DIw==,type:str]
    version: 3.13.0
