alertmanager:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: alertmanager.hariharanep4.space
      external-dns.alpha.kubernetes.io/target: 26016222-ecef-4643-b9b5-0a28c04de49c.cfargotunnel.com
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingressClassName: "nginx"
    hosts: 
    - alertmanager.hariharanep4.space
    paths:
    - /
grafana:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: grafana.hariharanep4.space
      external-dns.alpha.kubernetes.io/target: 26016222-ecef-4643-b9b5-0a28c04de49c.cfargotunnel.com
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingressClassName: "nginx"
    hosts:
    - grafana.hariharanep4.space
    path: /
prometheus:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: prometheus.hariharanep4.space
      external-dns.alpha.kubernetes.io/target: 26016222-ecef-4643-b9b5-0a28c04de49c.cfargotunnel.com
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingressClassName: "nginx"
    hosts:
    - prometheus.hariharanep4.space
    paths:
    - /
