apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: podinfo.hariharanep4.space
          paths:
            - path: /
              pathType: ImplementationSpecific
      annotations:
        external-dns.alpha.kubernetes.io/target: "26016222-ecef-4643-b9b5-0a28c04de49c.cfargotunnel.com"
        external-dns.alpha.kubernetes.io/hostname: podinfo.hariharanep4.space
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
