---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: 8-demo-image-update-bb-app
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: 8-demo
    commit:
      author:
        email: "hariharanep@gmail.com"
        name: "Hariharan E"
    push:
      branch: 8-demo
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: 8-demo-source-git-bb-app
  update:
    path: ./manifests
    strategy: Setters
